### PR TITLE
updated lodash to ~3.10.0

### PR DESCRIPTION
**Pull request by manikandants**

### CODE REVIEW

**Comment by gustavohenke** [comment]
Why those changes?

**Comment by manikandants** [comment]
I upgraded lodash to 3.10.0 and installed grunt-jscs in my project. I got an error during installation so upgraded the version here. But it seems to be the behavior of npm 3. Downgraded npm to 2.13.2 and everything works fine.

**Comment by gustavohenke** [comment]
You made lots of unrelated changes, that's why I asked.

Anyway, what's the error you got?

**Comment by markelog** [comment]
Oops, sorry, did that in https://github.com/jscs-dev/grunt-jscs/commit/3f2499e1122a447c46add9b0d3cd4393cb750d15

**Pull request closed without merging**
