### PR TITLE
Update jscs to 3.0

### PR DESCRIPTION
**Pull request by paladox**
Jscs is now deprecated and will no longer be updated.

It will only have bug fixes for three months and instead they are moving to eslint.

### CODE REVIEW

**Comment by gustavohenke** [comment]
Could you please take a look on the errors that are going on in the unit tests?

**Comment by tclindner** [comment]
@paladox would you mind reviewing your PR? I'm interested in your update!

**Comment by markelog** [comment]
Yeah, i was waiting to do the support for 3.x release since it was shaky for a while, still is though, i'm hoping incoming 3.0.4 release would cover most of the issues

**Comment by paladox** [comment]
Ok, I'm not sure why it is failing

236Testing methods.js...............Warning: Object #<Object> has no method 'getSourceCodeLength' Use --force to continue.

**Comment by paladox** [comment]
I used verbose and tracked it down to this line

https://github.com/jscs-dev/grunt-jscs/blob/master/test/methods.js#L279

per https://travis-ci.org/jscs-dev/grunt-jscs/jobs/130201258

**Pull request closed without merging**
